backend:
  name: github
  repo: nicholaslck/nicholaslck.github.io
  branch: main
  base_url: https://decap-proxy.nicholaslck.workers.dev

media_folder: 'static/uploads' # Folder where media files will be stored
public_folder: '/uploads' # Folder where media files will be accessible
site_url: https://nicholaslck.github.io
display_url: https://nicholaslck.github.io

collections:
  - name: 'configs'
    label: 'Configs'
    files:
      - label: 'Global'
        name: 'global'
        file: 'content/configs/global.md'
        fields:
          - { label: Site title, name: site_title, widget: string }
          - { label: Site description, name: site_description, widget: text }
          - { label: Avatar, name: avatar, widget: image }

  - name: 'blogs'
    label: 'Blogs'
    folder: 'content/blogs'
    create: true
    slug: '{{uuid_shorter}}-{{slug}}'
    sortable_fields:
      fields: [title, created_at]
      default:
        field: created_at
        direction: descending
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Created at', name: 'created_at', widget: 'datetime', default: '{{now}}' }
      - { label: 'Abstract', name: 'abstract', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'tags'
    label: 'Tags'
    folder: 'content/tags'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Color', name: 'color', widget: 'color' }

  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Cover image', name: 'cover_image', widget: 'image' }
      - {
          label: 'URL',
          name: 'url',
          widget: 'string',
          required: false,
          hint: 'Redirect URL to the project page'
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }

  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Blog list'
        name: 'blog-list'
        file: 'content/pages/blog-list.md'
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: text }
      - label: 'Project list'
        name: 'project-list'
        file: 'content/pages/project-list.md'
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: text }
