backend:
  name: github
  repo: nicholaslck/nicholaslck.github.io
  branch: main
  base_url: https://decap-proxy.nicholaslck.workers.dev

media_folder: 'static/uploads' # Folder where media files will be stored
public_folder: '/uploads' # Folder where media files will be accessible
site_url: https://nicholaslck.github.io
display_url: https://nicholaslck.github.io

singletons:
  - label: 'Resume file'
    name: 'resume_file'
    file: 'content/resume_file.md'
    fields:
      - { label: Resume file, name: file, widget: file, hint: 'Upload your resume in PDF format' }
      - { label: Last updated, name: last_updated, widget: datetime, default: '{{now}}' }

collections:
  - name: 'configs'
    label: 'Configs'
    files:
      - label: 'Global'
        name: 'global'
        file: 'content/configs/global.md'
        fields:
          - { label: Site title, name: site_title, widget: string }
          - { label: Site description, name: site_description, widget: text }
          - { label: Avatar, name: avatar, widget: image }

  - name: 'blogs'
    label: 'Blogs'
    folder: 'content/blogs'
    create: true
    slug: '{{uuid_shorter}}-{{slug}}'
    sortable_fields:
      fields: [title, created_at]
      default: { field: created_at, direction: descending }
    view_filters:
      - { label: 'Published', field: 'published', pattern: true }
      - { label: 'Drafts', field: 'published', pattern: false }
    fields:
      - { label: 'Published', name: 'published', widget: 'boolean', default: true }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Created at', name: 'created_at', widget: 'datetime', default: '{{now}}' }
      - { label: 'Abstract', name: 'abstract', widget: 'text' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'relation',
          collection: 'tags',
          search_fields: ['name'],
          value_field: 'name',
          display_fields: ['name'],
          multiple: true,
          required: false
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'tags'
    label: 'Tags'
    folder: 'content/tags'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Color', name: 'color', widget: 'color' }

  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    create: true
    slug: '{{slug}}'
    sortable_fields:
      fields: ['date']
      default: { field: date, direction: descending }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Cover image', name: 'cover_image', widget: 'image', required: false }
      - {
          label: 'URL',
          name: 'url',
          widget: 'string',
          required: false,
          hint: 'Redirect URL to the project page'
        }
      - {
          label: 'Type',
          name: 'type',
          widget: 'select',
          options: ['work_project', 'mphil_project', 'self_project', 'freelance_project']
        }
      - { label: 'Date', name: 'date', widget: 'datetime', time_format: false }
      - {
          label: 'Coming soon',
          name: 'coming_soon',
          widget: 'boolean',
          default: false,
          required: false,
          hint: 'Mark as coming soon if the project is not yet launched'
        }
      - {
          label: 'Related work experience',
          name: 'related_work_experience',
          widget: 'relation',
          collection: 'work_experiences',
          search_fields: ['company'],
          value_field: 'company',
          display_fields: ['company'],
          required: false
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }

  - name: 'educations'
    label: 'Educations'
    folder: 'content/educations'
    create: true
    slug: '{{slug}}'
    sortable_fields:
      fields: ['start_date', 'end_date']
      default: { field: start_date, direction: descending }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Institution', name: 'institution', widget: 'string' }
      - { label: 'Degree', name: 'degree', widget: 'string' }
      - { label: 'Start date', name: 'start_date', widget: 'datetime', time_format: false }
      - { label: 'End date', name: 'end_date', widget: 'datetime', time_format: false }
      - { label: 'Is current', name: 'is_current', widget: 'boolean' }

  - name: 'certifications'
    label: 'Certifications'
    folder: 'content/certifications'
    create: true
    slug: '{{slug}}'
    sortable_fields:
      fields: ['start_date', 'end_date']
      default: { field: start_date, direction: descending }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Institution', name: 'institution', widget: 'string' }
      - { label: 'Start date', name: 'start_date', widget: 'datetime', time_format: false }
      - { label: 'End date', name: 'end_date', widget: 'datetime', time_format: false }

  - name: 'work_experiences'
    label: 'Work Experiences'
    folder: 'content/work_experiences'
    create: true
    slug: '{{company}}-{{position}}'
    summary: '{{company}} - {{position}}'
    sortable_fields:
      fields: ['start_date', 'end_date']
      default: { field: start_date, direction: descending }
    fields:
      - { label: 'Icon', name: 'icon', widget: 'image' }
      - { label: 'Company', name: 'company', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - { label: 'Start date', name: 'start_date', widget: 'datetime' }
      - { label: 'End date', name: 'end_date', widget: 'datetime', required: false }
      - { label: 'Is current', name: 'is_current', widget: 'boolean' }

  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Blog list'
        name: 'blog-list'
        file: 'content/pages/blog-list.md'
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: text }
      - label: 'Project list'
        name: 'project-list'
        file: 'content/pages/project-list.md'
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: text }
